/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sigmaray;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author patrick
 */
public class Carousel extends javax.swing.JFrame {

    /**
     * Creates new form Carousel
     */
    public Carousel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Pasta");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        downloadUrlListInThread();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carousel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carousel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carousel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carousel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carousel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


    List urlsList = new ArrayList();
    int imageIndex = 0;
    int page = 0;
    BufferedImage imageToDownload;

    private void downloadUrlListInThread() {
        downloadUrlListInThread(0);
    }
    
    private void downloadUrlListInThread(int page) {
        final String s = jTextField1.getText();
        if (s == "") {
            return;
        }
//        disableButtons();
//        jLabel3.setText("Downloading URLs...");
        final int ppp = page;
        Thread t = new Thread() {
            @Override
            public void run() {
                urlsList = JavaFlickr.flickrListToUrlList(JavaFlickr.getList(s, ppp));

//                try {
//                    Thread.sleep(10000);
//                } catch (InterruptedException ex) {
//                    Logger.getLogger(NFlickrGUI.class.getName()).log(Level.SEVERE, null, ex);
//                }
                SwingUtilities.invokeLater(
                        new Runnable() {
                            public void run() {
//                                jLabel3.setText("");
                                imageIndex = 0;
                                downloadFirstImageInThread();
                            }
                        }
                );
            }
        };
        t.start();
    }
    
    private void downloadFirstImageInThread() {
//        disableButtons();
        Thread t = new Thread() {
            @Override
            public void run() {
                BufferedImage img = downloadImage((String) urlsList.get(imageIndex));
                imageToDownload = img;
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Carousel.class.getName()).log(Level.SEVERE, null, ex);
                }
                SwingUtilities.invokeLater(
                        new Runnable() {
                            public void run() {
                                jLabel1.setIcon(new javax.swing.ImageIcon(imageToDownload));
//                                enableButtons();
                                downloadNextImageInThread();
                            }
                        }
                );
            }
        };
        t.start();
    }

    private void downloadNextImageInThread() {
        if (imageIndex == (urlsList.size() - 1)) {
//            return;
            imageIndex = 0;
            page++;
            urlsList = new ArrayList();
            downloadUrlListInThread(page);
            return;
        }
        imageIndex++;
//        disableButtons();
        Thread t = new Thread() {
            @Override
            public void run() {
                BufferedImage img = downloadImage((String) urlsList.get(imageIndex));
                imageToDownload = img;
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Carousel.class.getName()).log(Level.SEVERE, null, ex);
                }
                SwingUtilities.invokeLater(
                        new Runnable() {
                            public void run() {
                                jLabel1.setIcon(new javax.swing.ImageIcon(imageToDownload));
//                                enableButtons();
                                downloadNextImageInThread();
                            }
                        }
                );
            }
        };
        t.start();
    }
    
    private BufferedImage downloadImage(String fullUrlPath) {
        BufferedImage img = null;
        try {
            URL url = new URL(fullUrlPath);
            img = ImageIO.read(url);
            ImageIcon icon = new ImageIcon(img);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return img;
    }
}
